# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 0.2.x ]
  pull_request:
    branches: [ 0.2.x ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
      COVERALLS_GIT_BRANCH: "${{ github.ref }}"
      COVERALLS_SERVICE_NAME: "Github CI"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Install npm dependencies
        run: npm install

      - name: Build node-red-contrib package
        run: npm run prepublishOnly

      - name: Launch unit testing
        run: npm run test 

      - name: Launch coverage update
        run: npm run coverage
         
  
  e2e-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        browser: [chrome, edge, safari, firefox]
        exclude:
          - os: macos-latest
            browser: edge #because its webdriver is buggy
          - os: windows-latest
            browser: safari
          - os: ubuntu-latest
            browser: safari
          - os: ubuntu-latest
            browser: edge
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Install npm dependencies
        run: npm install

      - name: Build node-red-contrib package
        run: npm run prepublishOnly

      - name: Run chromedriver
        if: ${{ matrix.browser == 'chrome' }}
        run: chromedriver & 

      - name: Run geckodriver
        if: ${{ matrix.browser == 'firefox' }}
        run: geckodriver -v > ubuntu-gecko-log.txt 2>&1 &

      - name: Run msedgedriver
        if: ${{ matrix.browser == 'edge' }}
        run: msedgedriver --port=9415 & 

      - name: Enable safaridriver
        if: ${{ matrix.browser == 'safari' }}
        run: sudo safaridriver --enable

      - name: Run safaridriver
        if: ${{ matrix.browser == 'safari' }}
        run: safaridriver --port 9315 & 


      - name: Run test with webdriver (ubuntu)
        if: ${{ matrix.os == "ubuntu-latest"}}
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test-wd-${{ matrix.browser }}

      - name: Run test with webdriver (others)
        if: ${{ matrix.os != "ubuntu-latest"}}
        run: npm run test-wd-${{ matrix.browser }}

#      - name: Install newman
#        run: sudo npm install -g newman
          
      # Runs a single command using the runners shell
#      - name: Run node-red
#        run: npx node-red > ${{ matrix.os }}-node-red-log.txt &

#      - name: Wait on
#        uses: iFaxity/wait-on-action@v1
#        with:
#          resource: http://localhost:1880/flows  
      
#      - name : Publish flows to node-red
#        run: newman run ./test/newman/init.json

#      - name : Test flows
#        run: newman run ./test/newman/test-suite1.json

#      - name: Upload artifact > node-red log
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2.2.2
#        with:
#          name: ${{ matrix.os }}-node-red-log
#          path: ./${{ matrix.os }}-node-red-log.txt

      - name: Upload artifact > ubuntu-gecko-log
        if: ${{ always() && matrix.os == 'ubuntu-latest' && matrix.browser == 'firefox' }}
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ubuntu-gecko-log
          path: ./ubuntu-gecko-log.txt
